# Generated by Django 3.2.16 on 2023-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='id',
        ),
        migrations.AddField(
            model_name='expenses',
            name='idOfExpense',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
