# Generated by Django 3.2.16 on 2023-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0002_auto_20230116_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='idOfExpense',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
