# Generated by Django 3.2.16 on 2023-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0003_alter_expenses_idofexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='idOfExpense',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
