# Generated by Django 3.2.16 on 2023-01-16 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0004_alter_expenses_idofexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 10, 15, 36, 407794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='atDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 10, 15, 36, 407794, tzinfo=utc)),
        ),
    ]
